Pjcoordinador_PrRamos/Models/ViewModels/ListadoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Pjcoordinador_PrRamos.Models.ViewModels
{
    public class ListadoViewModel
    {
        public int idRequisicion { get; set; }
        public string detalleRequisicion { get; set; }
        public decimal cantidad { get; set; }
        public decimal precioUnitaro { get; set; }
        public decimal total { get; set; }
        public string idEmpleadoSolicita { get; set; }
        public DateTime fechaSolicita { get; set; }
        public string Estado { get; set; }
        public DateTime fechaGrabada { get; set; }
        public int idEmpleado { get; set; }
        public int idEstado { get; set; }

        public string estado { get; set; }
    }
}

Pjcoordinador_PrRamos/Models/ViewModels/NuevoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Pjcoordinador_PrRamos.Models.ViewModels
{
    public class NuevoViewModel
    {
        public int idRequisicion { get; set; }
        [Required]
        [Display(Name ="Detalle")]
        [StringLength(200)]
        public string detalleRequisicion { get; set; }
        [Required]
        [Display(Name = "Cantidad")]
        [Range(0, int.MaxValue, ErrorMessage = "Ingresar solo numeros enteros")]
        public decimal cantidad { get; set; }
        [Required]
        [Display(Name = "Precio Unitario")]
        [RegularExpression(@"^\d+\.\d{0,2}$")]
        [Range(0, 9999999999999999.99)]
        public decimal precioUnitaro { get; set; }
        [Required]
        [Display(Name = "Total")]
        [RegularExpression(@"^\d+\.\d{0,2}$")]
        [Range(0, 9999999999999999.99)]
        public decimal total { get; set; }
        [Required]
        [Display(Name = "Empleado solicitante")]
        [Range(0, int.MaxValue, ErrorMessage = "Ingrese un numero de Id porfavor")]
        public int idEmpleadoSolicita { get; set; }
        public string Estado { get; set; }
        public int idEstado { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de requisición")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime fechaSolicita { get; set; }
        public System.DateTime fechaGrabada { get; set; }
    }
}

Pjcoordinador_PrRamos/Controllers/ListadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Pjcoordinador_PrRamos.Models;
using Pjcoordinador_PrRamos.Models.ViewModels;

namespace Pjcoordinador_PrRamos.Models
{
    public class ListadoController : Controller
    {
        // GET: Listado
        public ActionResult Index()
        {
            List<ListadoViewModel> lst = null;
            int userid = (int)Session["IdUser"];
            int puesto = (int)Session["IdPuesto"];

            if (puesto == 1) {
            using (DBcoordinador_RamosEntities4 db = new DBcoordinador_RamosEntities4())
            {
                //lst = (from d in db.View_requisiciones
                //       select new ListadoViewModel
                lst = (from d in db.View_requisiciones
                       where d.idEmpleadoSolicita == userid
                       select new ListadoViewModel
                       {
                           idRequisicion = d.idRequisicion,
                           detalleRequisicion = d.detalleRequisicion,
                           cantidad = d.cantidad,
                           precioUnitaro = d.precioUnitario,
                           total = d.total,
                           idEmpleadoSolicita = d.usuario,
                           fechaSolicita = d.fechaSolicita,
                           Estado = d.estado,
                           fechaGrabada = d.fechaGraba
                       }).ToList();
            }
            }
            else if (puesto == 2)
            {
                using (DBcoordinador_RamosEntities4 db = new DBcoordinador_RamosEntities4())
                {
                    lst = (from d in db.View_requisiciones
                           select new ListadoViewModel
                           {
                               idRequisicion = d.idRequisicion,
                               detalleRequisicion = d.detalleRequisicion,
                               cantidad = d.cantidad,
                               precioUnitaro = d.precioUnitario,
                               total = d.total,
                               idEmpleadoSolicita = d.usuario,
                               fechaSolicita = d.fechaSolicita,
                               Estado = d.estado,
                               fechaGrabada = d.fechaGraba
                           }).ToList();
                }
            }
            return View(lst);
        }

        public ActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(NuevoViewModel model)
        {
            int userid = (int)Session["IdUser"];
            try
            {
                if (ModelState.IsValid)
                {
                    using (DBcoordinador_RamosEntities2 db = new DBcoordinador_RamosEntities2())
                    {
                        var oTabla = new t_Requisiciones();
                        oTabla.detalleRequisicion = model.detalleRequisicion;
                        oTabla.cantidad = model.cantidad;
                        oTabla.precioUnitario = model.precioUnitaro;
                        oTabla.total = model.total;
                        oTabla.idEmpleadoSolicita = userid;
                        oTabla.fechaSolicita = model.fechaSolicita;
                        oTabla.idEstado = 1;
                        oTabla.fechaGraba = DateTime.Now;

                        db.t_Requisiciones.Add(oTabla);
                        db.SaveChanges();
                    }

                    return Redirect("~/Listado/");
                }

                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Editar(int Id)
        {
            NuevoViewModel model = new NuevoViewModel();
            List<ListadoViewModel> lst = null;
            using (DBcoordinador_RamosEntities2 db = new DBcoordinador_RamosEntities2())
            {
                var oRequi = db.t_Requisiciones.Find(Id);
                model.idRequisicion = oRequi.idRequisicion;
                model.detalleRequisicion = oRequi.detalleRequisicion;
                model.cantidad = oRequi.cantidad;
                model.precioUnitaro = oRequi.precioUnitario;
                model.total = oRequi.total;
                model.fechaSolicita = oRequi.fechaSolicita;
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(NuevoViewModel model)
        {
            int userid = (int)Session["IdUser"];
            try
            {
                if (ModelState.IsValid)
                {
                    using (DBcoordinador_RamosEntities2 db = new DBcoordinador_RamosEntities2())
                    {
                        var oRequi = db.t_Requisiciones.Find(model.idRequisicion);
                        oRequi.detalleRequisicion = model.detalleRequisicion;
                        oRequi.cantidad = model.cantidad;
                        oRequi.precioUnitario = model.precioUnitaro;
                        oRequi.total = model.total;
                        oRequi.idEmpleadoSolicita = userid;
                        oRequi.fechaSolicita = model.fechaSolicita;
                        oRequi.idEstado = 1;
                        oRequi.fechaGraba = DateTime.Now;

                        db.Entry(oRequi).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }

                    return Redirect("~/Listado/");
                }

                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int Id)
        {
            using (DBcoordinador_RamosEntities2 db = new DBcoordinador_RamosEntities2())
            {
                var oRequi = db.t_Requisiciones.Find(Id);
                db.t_Requisiciones.Remove(oRequi);
                db.SaveChanges();
            }
            return Redirect("~/Listado/");
        }

        public ActionResult Revision(int Id)
        {
            List<ListadoViewModel> lst = null;
            NuevoViewModel model = new NuevoViewModel();
            using (DBcoordinador_RamosEntities2 db = new DBcoordinador_RamosEntities2())
            {
                var oRequi = db.t_Requisiciones.Find(Id);
                model.idRequisicion = oRequi.idRequisicion;
                model.detalleRequisicion = oRequi.detalleRequisicion;
                model.cantidad = oRequi.cantidad;
                model.precioUnitaro = oRequi.precioUnitario;
                model.total = oRequi.total;
                model.fechaSolicita = oRequi.fechaSolicita;
                model.idEmpleadoSolicita = oRequi.idEmpleadoSolicita;
                model.idEstado = oRequi.idEstado;

                lst =
                    (from d in db.c_Estado
                     select new ListadoViewModel
                     {
                         idEstado = d.idEstado,
                         estado = d.estado
                     }).ToList();

            }

            List<SelectListItem> item = lst.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.estado.ToString(),
                    Value = d.idEstado.ToString(),
                    Selected = false
                };
            });

            ViewBag.items = item;

            return View(model);
        }

        [HttpPost]
        public ActionResult Revision(NuevoViewModel model, FormCollection form)
        {
            try
            {                
                if (ModelState.IsValid)
                {
                    using (DBcoordinador_RamosEntities2 db = new DBcoordinador_RamosEntities2())
                    {
                        string State = form["Estados"];
                        var oRequi = db.t_Requisiciones.Find(model.idRequisicion);
                        oRequi.idEstado = int.Parse(State);
                        oRequi.fechaGraba = DateTime.Now;

                        db.Entry(oRequi).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }

                    int userid = (int)Session["IdUser"];
                    using (DBcoordinador_RamosEntities5 db = new DBcoordinador_RamosEntities5())
                    {
                        string State = form["Estados"];

                        var oTabla = new t_RequisicionesBitacora();
                        oTabla.idRequisicion = model.idRequisicion;
                        oTabla.idEstadoAnterior = model.idEstado;
                        oTabla.idEstadoNuevo = int.Parse(State);
                        oTabla.fechaRegistro = DateTime.Now;
                        oTabla.observacion = "SE HICIERON CAMBIOS";
                        oTabla.idEmpleadoRegistra = userid;

                        db.t_RequisicionesBitacora.Add(oTabla);
                        db.SaveChanges();
                    }

                    return Redirect("~/Listado/");
                }

                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

Pjcoordinador_PrRamos/Views/Listado/Editar.cshtml
@model Pjcoordinador_PrRamos.Models.ViewModels.NuevoViewModel
@{
    ViewBag.Title = "Editar";
    ViewBag.cant = 0;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Editar", "Listado", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.idRequisicion)
            <div>
                @Html.LabelFor(d => d.fechaSolicita)<br />
                @Html.EditorFor(d => d.fechaSolicita, "", new { @class = "form-control" })<br /><br />
                @Html.ValidationMessageFor(d => d.fechaSolicita, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.detalleRequisicion)
                @Html.TextBoxFor(d => d.detalleRequisicion, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.detalleRequisicion, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.cantidad)
                @Html.TextBoxFor(d => d.cantidad, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.cantidad, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.precioUnitaro)
                @Html.TextBoxFor(d => d.precioUnitaro, "", new { @class = "form-control", @onfocusout = "calcular();" })
                @Html.ValidationMessageFor(d => d.precioUnitaro, null, new { @class = "red" })
            </div>
            <div>
                @*@Html.LabelFor(d => d.total)
                    @Html.TextBoxFor(d => d.total, "", new { @class = "form-control", @readonly = "readonly" })*@
                @Html.LabelFor(d => d.total)
                @Html.TextBoxFor(d => d.total, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.total, null, new { @class = "red" })
            </div>
            <br />
            <div style="text-align:right">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>
    </div>
    <script>
        function calcular() {
            var cant = document.getElementById('cantidad').value;
            var precio = document.getElementById('precioUnitaro').value;

            var total = parseFloat(cant) * parseFloat(precio)

            $("#total").val(total);
            $("#total").change();

        }
    </script>
}

Pjcoordinador_PrRamos/Views/Listado/Index.cshtml
@model List<Pjcoordinador_PrRamos.Models.ViewModels.ListadoViewModel>
@{
    ViewBag.Title = "Listado de Requisiciones";
    int puesto = (int)Session["IdPuesto"];
}

<h2>@ViewBag.Title</h2>

<div class="row" style="text-align:right;padding:5px">
    <a href="~/Listado/Nuevo" class="btn btn-primary">Nuevo</a>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>#</th>
                <th>Det_Requisicion</th>
                <th>Cantidad</th>
                <th>Precio_Unitario</th>
                <th>Total</th>
                <th>Empleado_Solicita</th>
                <th>Fecha_Solicita</th>
                <th>Estado</th>
                <th>Fecha_Grabada</th>
                <th></th>
            </tr>
            @foreach (var oElemento in Model)
            {
        <tr>
            <td>@oElemento.idRequisicion</td>
            <td>@oElemento.detalleRequisicion</td>
            <td>@oElemento.cantidad</td>
            <td>@oElemento.precioUnitaro</td>
            <td>@oElemento.total</td>
            <td>@oElemento.idEmpleadoSolicita</td>
            <td>@oElemento.fechaSolicita</td>
            <td>@oElemento.Estado</td>
            <td>@oElemento.fechaGrabada</td>
            <td>
                @if (puesto == 1)
                {
                    <a class="btn btn-default" href="~/Listado/Editar/@oElemento.idRequisicion">Editar</a>
                    <a class="btn btn-danger" href="~/Listado/Eliminar/@oElemento.idRequisicion">Desactivar</a>
                }
                else if (puesto == 2)
                {
                    <a class="btn btn-default" href="~/Listado/Editar/@oElemento.idRequisicion">Editar</a>
                    <a class="btn btn-danger" href="~/Listado/Eliminar/@oElemento.idRequisicion">Desactivar</a><br /><br />
                    <a class="btn btn-success" href="~/Listado/Revision/@oElemento.idRequisicion">Revisar</a>
                }
            </td>
        </tr>
            }
        </table>
    </div>
</div>

Pjcoordinador_PrRamos/Views/Listado/Nuevo.cshtml
@model Pjcoordinador_PrRamos.Models.ViewModels.NuevoViewModel
@{
    ViewBag.Title = "Nuevo";
    ViewBag.cant = 0;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Nuevo", "Listado", FormMethod.Post)) {
<div class="row">
    <div class="col-md-12">
        <div>
            @Html.LabelFor(d => d.fechaSolicita)<br />
            @Html.EditorFor(d => d.fechaSolicita, "", new { @class = "form-control" })<br /><br />
            @Html.ValidationMessageFor(d => d.fechaSolicita, null, new { @class = "red" })
        </div>
        <div>
            @Html.LabelFor(d => d.detalleRequisicion)
            @Html.TextBoxFor(d => d.detalleRequisicion, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.detalleRequisicion, null, new { @class = "red" })
        </div>
        <div>
            @Html.LabelFor(d => d.cantidad)
            @Html.TextBoxFor(d => d.cantidad, "", new { @class = "form-control", Value = ViewBag.cant })
            @Html.ValidationMessageFor(d => d.cantidad, null, new { @class = "red" })
        </div>
        <div>
            @Html.LabelFor(d => d.precioUnitaro)
            @*@Html.TextBoxFor(d => d.precioUnitaro, "", new { @class = "form-control", @onkeypress = "keypresshandle(event);" })*@
            @Html.TextBoxFor(d => d.precioUnitaro, "", new { @class = "form-control", @onfocusout = "calcular();" })
            @Html.ValidationMessageFor(d => d.precioUnitaro, null, new { @class = "red" })
        </div>
        <div>
            @*@Html.LabelFor(d => d.total)
        @Html.TextBoxFor(d => d.total, "", new { @class = "form-control", @readonly = "readonly" })*@
            @Html.LabelFor(d => d.total)
            @Html.TextBoxFor(d => d.total, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.total, null, new { @class = "red" })
        </div>
        <br />
        <div style="text-align:right">
            <input value="Guardar" class="btn btn-primary" type="submit" />
        </div>
    </div>
</div>
<script>
    function keypresshandle(e) {
        if (e.keyCode == 13) {
            e.preventDefault();
            var cant = document.getElementById('cantidad').value;
            var precio = document.getElementById('precioUnitaro').value;

            var total = parseFloat(cant) * parseFloat(precio)

            $("#total").val(total);
            $("#total").change();
        }
    }
    function calcular() {
            var cant = document.getElementById('cantidad').value;
            var precio = document.getElementById('precioUnitaro').value;

            var total = parseFloat(cant) * parseFloat(precio)

            $("#total").val(total);
            $("#total").change();

    }
</script>
}

Pjcoordinador_PrRamos/Views/Listado/Revision.cshtml
@model Pjcoordinador_PrRamos.Models.ViewModels.NuevoViewModel
@{
    ViewBag.Title = "Revision";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Revision", "Listado", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.idRequisicion)
            <div>
                @Html.LabelFor(d => d.fechaSolicita)<br />
                @Html.EditorFor(d => d.fechaSolicita, "", new { @class = "form-control", @readonly = "readonly" })<br /><br />
                @Html.ValidationMessageFor(d => d.fechaSolicita, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.detalleRequisicion)
                @Html.TextBoxFor(d => d.detalleRequisicion, "", new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(d => d.detalleRequisicion, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.cantidad)
                @Html.TextBoxFor(d => d.cantidad, "", new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(d => d.cantidad, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.precioUnitaro)
                @Html.TextBoxFor(d => d.precioUnitaro, "", new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(d => d.precioUnitaro, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.total)
                @Html.TextBoxFor(d => d.total, "", new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(d => d.total, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.idEmpleadoSolicita)
                @Html.TextBoxFor(d => d.idEmpleadoSolicita, "", new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(d => d.idEmpleadoSolicita, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.idEstado)
                @Html.TextBoxFor(d => d.idEstado, "", new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(d => d.idEstado, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Estado)
                @Html.DropDownList("Estados", items, "Seleccionar un estado", new { @class = "form-control" })
                @Html.HiddenFor(d => d.Estado)
                @*@Html.LabelFor(d => d.idEstado)
        @Html.TextBoxFor(d => d.idEstado, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(d => d.idEstado, null, new { @class = "red" })*@
            </div>
            <br />
            <div style="text-align:right">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>
        </div>
    </div>
}